INSERT INTO
    concours (
        LIBEL_SH,
        LIBEL_L,
        DATE_FIN,
        ID_SOUS_THEME
    )
VALUES
    (
        "Internal Quality Liaison",
        "synthesizing the alarm won't do anything, we need to hack the redundant THX circuit!",
        "2020-08-24T03:35:20.779Z",
        "1"
    ),
    (
        "Legacy Program Specialist",
        "I'll override the primary ADP interface, that should sensor the XSS matrix!",
        "2021-07-16T05:05:45.251Z",
        "1"
    ),
    (
        "Lead Identity Orchestrator",
        "Try to synthesize the AI sensor, maybe it will back up the back-end array!",
        "2020-10-05T20:14:25.462Z",
        "1"
    ),
    (
        "Internal Quality Liaison",
        "synthesizing the alarm won't do anything, we need to hack the redundant THX circuit!",
        "2020-08-24T03:35:20.779Z",
        "2"
    ),
    (
        "Legacy Program Specialist",
        "I'll override the primary ADP interface, that should sensor the XSS matrix!",
        "2021-07-16T05:05:45.251Z",
        "2"
    ),
    (
        "Lead Identity Orchestrator",
        "Try to synthesize the AI sensor, maybe it will back up the back-end array!",
        "2020-10-05T20:14:25.462Z",
        "2"
    ),
    (
        "Internal Quality Liaison",
        "synthesizing the alarm won't do anything, we need to hack the redundant THX circuit!",
        "2020-08-24T03:35:20.779Z",
        "3"
    ),
    (
        "Internal Quality Liaison",
        "synthesizing the alarm won't do anything, we need to hack the redundant THX circuit!",
        "2020-08-24T03:35:20.779Z",
        "3"
    ),
    (
        "Legacy Program Specialist",
        "I'll override the primary ADP interface, that should sensor the XSS matrix!",
        "2021-07-16T05:05:45.251Z",
        "3"
    ),
    (
        "Lead Identity Orchestrator",
        "Try to synthesize the AI sensor, maybe it will back up the back-end array!",
        "2020-10-05T20:14:25.462Z",
        "3"
    ),
    (
        "Internal Quality Liaison",
        "synthesizing the alarm won't do anything, we need to hack the redundant THX circuit!",
        "2020-08-24T03:35:20.779Z",
        "4"
    ),
    (
        "Legacy Program Specialist",
        "I'll override the primary ADP interface, that should sensor the XSS matrix!",
        "2021-07-16T05:05:45.251Z",
        "4"
    ),
    (
        "Lead Identity Orchestrator",
        "Try to synthesize the AI sensor, maybe it will back up the back-end array!",
        "2020-10-05T20:14:25.462Z",
        "4"
    ),
    (
        "Internal Quality Liaison",
        "synthesizing the alarm won't do anything, we need to hack the redundant THX circuit!",
        "2020-08-24T03:35:20.779Z",
        "5"
    ),
    (
        "Legacy Program Specialist",
        "I'll override the primary ADP interface, that should sensor the XSS matrix!",
        "2021-07-16T05:05:45.251Z",
        "5"
    ),
    (
        "Lead Identity Orchestrator",
        "Try to synthesize the AI sensor, maybe it will back up the back-end array!",
        "2020-10-05T20:14:25.462Z",
        "5"
    );

INSERT INTO
    inscription (ID_USER, ID_STATUT, ID_CONCOURS)
VALUES
    ("1", "1", "1"),
    ("1", "1", "2"),
    ("1", "2", "3"),
    ("1", "3", "4"),
    ("2", "1", "1"),
    ("2", "1", "2"),
    ("2", "2", "3"),
    ("2", "3", "4"),
    ("3", "1", "1"),
    ("3", "1", "2"),
    ("3", "2", "3"),
    ("3", "3", "4");

INSERT INTO
    log (ID_USER, DATE_LOG, ACTION)
VALUES
    ("1", "2020-08-24T03:35:20.779Z", "insertion"),
    ("2", "2020-08-24T03:35:20.779Z", "lecture"),
    ("2", "2020-08-24T03:35:20.779Z", "insertion");

INSERT INTO
    nationalité (ID_NATIONALITE, NOM_NATIONALITE)
VALUES
    ('AF', 'Afghanistan'),
    ('ZA', 'Afrique du Sud'),
    ('AL', 'Albanie'),
    ('DZ', 'Algérie'),
    ('DE', 'Allemagne'),
    ('AD', 'Andorre'),
    ('AO', 'Angola'),
    ('AI', 'Anguilla'),
    ('AQ', 'Antarctique'),
    ('AG', 'Antigua-et-Barbuda'),
    ('AN', 'Antilles néerlandaises'),
    ('SA', 'Arabie saoudite'),
    ('AR', 'Argentine'),
    ('AM', 'Arménie'),
    ('AW', 'Aruba'),
    ('AU', 'Australie'),
    ('AT', 'Autriche'),
    ('AZ', 'Azerbaïdjan'),
    ('BJ', 'Bénin'),
    ('BS', 'Bahamas'),
    ('BH', 'Bahreïn'),
    ('BD', 'Bangladesh'),
    ('BB', 'Barbade'),
    ('PW', 'Belau'),
    ('BE', 'Belgique'),
    ('BZ', 'Belize'),
    ('BM', 'Bermudes'),
    ('BT', 'Bhoutan'),
    ('BY', 'Biélorussie'),
    ('MM', 'Birmanie'),
    ('BO', 'Bolivie'),
    ('BA', 'Bosnie-Herzégovine'),
    ('BW', 'Botswana'),
    ('BR', 'Brésil'),
    ('BN', 'Brunei'),
    ('BG', 'Bulgarie'),
    ('BF', 'Burkina Faso'),
    ('BI', 'Burundi'),
    ('CI', 'Côte d''Ivoire'),
    ('KH', 'Cambodge'),
    ('CM', 'Cameroun'),
    ('CA', 'Canada'),
    ('CV', 'Cap-Vert'),
    ('CL', 'Chili'),
    ('CN', 'Chine'),
    ('CY', 'Chypre'),
    ('CO', 'Colombie'),
    ('KM', 'Comores'),
    ('CG', 'Congo'),
    ('KP', 'Corée du Nord'),
    ('KR', 'Corée du Sud'),
    ('CR', 'Costa Rica'),
    ('HR', 'Croatie'),
    ('CU', 'Cuba'),
    ('DK', 'Danemark'),
    ('DJ', 'Djibouti'),
    ('DM', 'Dominique'),
    ('EG', 'Égypte'),
    ('AE', 'Émirats arabes unis'),
    ('EC', 'Équateur'),
    ('ER', 'Érythrée'),
    ('ES', 'Espagne'),
    ('EE', 'Estonie'),
    ('US', 'États-Unis'),
    ('ET', 'Éthiopie'),
    ('FI', 'Finlande'),
    ('FR', 'France'),
    ('GE', 'Géorgie'),
    ('GA', 'Gabon'),
    ('GM', 'Gambie'),
    ('GH', 'Ghana'),
    ('GI', 'Gibraltar'),
    ('GR', 'Grèce'),
    ('GD', 'Grenade'),
    ('GL', 'Groenland'),
    ('GP', 'Guadeloupe'),
    ('GU', 'Guam'),
    ('GT', 'Guatemala'),
    ('GN', 'Guinée'),
    ('GQ', 'Guinée équatoriale'),
    ('GW', 'Guinée-Bissao'),
    ('GY', 'Guyana'),
    ('GF', 'Guyane française'),
    ('HT', 'Haïti'),
    ('HN', 'Honduras'),
    ('HK', 'Hong Kong'),
    ('HU', 'Hongrie'),
    ('BV', 'Ile Bouvet'),
    ('CX', 'Ile Christmas'),
    ('NF', 'Ile Norfolk'),
    ('KY', 'Iles Cayman'),
    ('CK', 'Iles Cook'),
    ('FO', 'Iles Féroé'),
    ('FK', 'Iles Falkland'),
    ('FJ', 'Iles Fidji'),
    ('GS', 'Iles Géorgie du Sud et Sandwich du Sud'),
    ('HM', 'Iles Heard et McDonald'),
    ('MH', 'Iles Marshall'),
    ('PN', 'Iles Pitcairn'),
    ('SB', 'Iles Salomon'),
    ('SJ', 'Iles Svalbard et Jan Mayen'),
    ('TC', 'Iles Turks-et-Caicos'),
    ('VI', 'Iles Vierges américaines'),
    ('VG', 'Iles Vierges britanniques'),
    ('CC', 'Iles des Cocos (Keeling)'),
    ('UM', 'Iles mineures éloignées des États-Unis'),
    ('IN', 'Inde'),
    ('ID', 'Indonésie'),
    ('IR', 'Iran'),
    ('IQ', 'Iraq'),
    ('IE', 'Irlande'),
    ('IS', 'Islande'),
    ('IL', 'Israël'),
    ('IT', 'Italie'),
    ('JM', 'Jamaïque'),
    ('JP', 'Japon'),
    ('JO', 'Jordanie'),
    ('KZ', 'Kazakhstan'),
    ('KE', 'Kenya'),
    ('KG', 'Kirghizistan'),
    ('KI', 'Kiribati'),
    ('KW', 'Koweït'),
    ('LA', 'Laos'),
    ('LS', 'Lesotho'),
    ('LV', 'Lettonie'),
    ('LB', 'Liban'),
    ('LR', 'Liberia'),
    ('LY', 'Libye'),
    ('LI', 'Liechtenstein'),
    ('LT', 'Lituanie'),
    ('LU', 'Luxembourg'),
    ('MO', 'Macao'),
    ('MG', 'Madagascar'),
    ('MY', 'Malaisie'),
    ('MW', 'Malawi'),
    ('MV', 'Maldives'),
    ('ML', 'Mali'),
    ('MT', 'Malte'),
    ('MP', 'Mariannes du Nord'),
    ('MA', 'Maroc'),
    ('MQ', 'Martinique'),
    ('MU', 'Maurice'),
    ('MR', 'Mauritanie'),
    ('YT', 'Mayotte'),
    ('MX', 'Mexique'),
    ('FM', 'Micronésie'),
    ('MD', 'Moldavie'),
    ('MC', 'Monaco'),
    ('MN', 'Mongolie'),
    ('MS', 'Montserrat'),
    ('MZ', 'Mozambique'),
    ('NP', 'Népal'),
    ('NA', 'Namibie'),
    ('NR', 'Nauru'),
    ('NI', 'Nicaragua'),
    ('NE', 'Niger'),
    ('NG', 'Nigeria'),
    ('NU', 'Nioué'),
    ('NO', 'Norvège'),
    ('NC', 'Nouvelle-Calédonie'),
    ('NZ', 'Nouvelle-Zélande'),
    ('OM', 'Oman'),
    ('UG', 'Ouganda'),
    ('UZ', 'Ouzbékistan'),
    ('PE', 'Pérou'),
    ('PK', 'Pakistan'),
    ('PA', 'Panama'),
    ('PG', 'Papouasie-Nouvelle-Guinée'),
    ('PY', 'Paraguay'),
    ('NL', 'Pays-Bas'),
    ('PH', 'Philippines'),
    ('PL', 'Pologne'),
    ('PF', 'Polynésie française'),
    ('PR', 'Porto Rico'),
    ('PT', 'Portugal'),
    ('QA', 'Qatar'),
    ('CF', 'République centrafricaine'),
    ('CD', 'République démocratique du Congo'),
    ('DO', 'République dominicaine'),
    ('CZ', 'République tchèque'),
    ('RE', 'Réunion'),
    ('RO', 'Roumanie'),
    ('GB', 'Royaume-Uni'),
    ('RU', 'Russie'),
    ('RW', 'Rwanda'),
    ('SN', 'Sénégal'),
    ('EH', 'Sahara occidental'),
    ('KN', 'Saint-Christophe-et-Niévès'),
    ('SM', 'Saint-Marin'),
    ('PM', 'Saint-Pierre-et-Miquelon'),
    ('VA', 'Saint-Siège '),
    ('VC', 'Saint-Vincent-et-les-Grenadines'),
    ('SH', 'Sainte-Hélène'),
    ('LC', 'Sainte-Lucie'),
    ('SV', 'Salvador'),
    ('WS', 'Samoa'),
    ('AS', 'Samoa américaines'),
    ('ST', 'Sao Tomé-et-Principe'),
    ('SC', 'Seychelles'),
    ('SL', 'Sierra Leone'),
    ('SG', 'Singapour'),
    ('SI', 'Slovénie'),
    ('SK', 'Slovaquie'),
    ('SO', 'Somalie'),
    ('SD', 'Soudan'),
    ('LK', 'Sri Lanka'),
    ('SE', 'Suède'),
    ('CH', 'Suisse'),
    ('SR', 'Suriname'),
    ('SZ', 'Swaziland'),
    ('SY', 'Syrie'),
    ('TW', 'Taïwan'),
    ('TJ', 'Tadjikistan'),
    ('TZ', 'Tanzanie'),
    ('TD', 'Tchad'),
    ('TF', 'Terres australes françaises'),
    ('IO', 'Territoire britannique de l`Océan Indien'),
    ('TH', 'Thaïlande'),
    ('TL', 'Timor Oriental'),
    ('TG', 'Togo'),
    ('TK', 'Tokélaou'),
    ('TO', 'Tonga'),
    ('TT', 'Trinité-et-Tobago'),
    ('TN', 'Tunisie'),
    ('TM', 'Turkménistan'),
    ('TR', 'Turquie'),
    ('TV', 'Tuvalu'),
    ('UA', 'Ukraine'),
    ('UY', 'Uruguay'),
    ('VU', 'Vanuatu'),
    ('VE', 'Venezuela'),
    ('VN', 'ViÃªtNam'),
    ('WF', 'Wallis-et-Futuna'),
    ('YE', 'Yémen'),
    ('YU', 'Yougoslavie'),
    ('ZM', 'Zambie'),
    ('ZW', 'Zimbabwe'),
    ('MK', 'ex-République yougoslave de Macédoine');

INSERT INTO
    photo (PATH_IMG, ID_PATH)
VALUES
    ("http://lorempixel.com/640/480/sports", "0"),
    ("http://lorempixel.com/640/480/nature", "1"),
    ("http://lorempixel.com/640/480/food", "2"),
    ("http://lorempixel.com/640/480/people", "3"),
    ("http://lorempixel.com/640/480/city", "4"),
    ("http://lorempixel.com/640/480/technics", "5"),
    ("http://lorempixel.com/640/480/nightlife", "6"),
    ("http://lorempixel.com/640/480/food", "7"),
    ("http://lorempixel.com/640/480/abstract", "8"),
    ("http://lorempixel.com/640/480/cats", "9"),
    ("http://lorempixel.com/640/480/transport", "10"),
    ("http://lorempixel.com/640/480/business", "11"),
    ("http://lorempixel.com/640/480/cats", "12"),
    ("http://lorempixel.com/640/480/fashion", "13"),
    ("http://lorempixel.com/640/480/people", "14"),
    ("http://lorempixel.com/640/480/sports", "15"),
    ("http://lorempixel.com/640/480/cats", "16"),
    ("http://lorempixel.com/640/480/abstract", "17"),
    ("http://lorempixel.com/640/480/city", "18"),
    ("http://lorempixel.com/640/480/food", "19"),
    ("http://lorempixel.com/640/480/cats", "20"),
    ("http://lorempixel.com/640/480/business", "21"),
    ("http://lorempixel.com/640/480/fashion", "22"),
    ("http://lorempixel.com/640/480/sports", "23"),
    ("http://lorempixel.com/640/480/nightfall", "24");

INSERT INTO
    role (ID_ROLE, ROLE)
VALUES
    ("0", "etudiant"),
    ("1", "equipe specialisé"),
    ("2", "equipe de recrutement"),
    ("3", "superadmin");

INSERT INTO
    soustheme(ID_SOUS_THEME, NOM_SOUS_THEME, ID_THEME)
VALUES
    ("1", "sous theme n°1 pompier", "1"),
    ("2", "sous theme n°2 infirmier", "1"),
    ("3", "sous theme n°3 random", "2"),
    ("4", "sous theme n°4 dev", "2"),
    ("5", "sous theme n°5 reseau", "3");

INSERT INTO
    theme(ID_THEME, NOM_THEME)
VALUES
    ("1", "theme aide a la personne"),
    ("2", "theme dev"),
    ("3", " theme reseau");

INSERT INTO
    statut(ID_STATUT, NOM_STATUT)
VALUES
    ("0", "transmis"),
    ("1", "en cours de traitement"),
    ("2", "validé"),
    ("3", "refusé");

INSERT INTO
    user(
        ID_USER,
        NOM,
        D_NAISS,
        SEXE,
        ADRESSE,
        TEL,
        COURRIEL,
        ETAT_CIVIL,
        ID_P,
        FACEBOOK,
        TWITTER,
        INSTAGRAM,
        MDP,
        PRENOM,
        ID_NATIONALITE,
        ID_ROLE
    )
VALUES
    (
        "1",
        "WILK",
        "1998-07-16T05:05:45.251Z",
        "1",
        "une adresse 24 avenue de savoie",
        "0809U9989898",
        "loubou@gmail.com",
        "etat civil",
        '123IO23I232302392',
        "lienfacebook",
        "lien twitter",
        "lien intagram",
        "mot de passe asher",
        "michal",
        "FR",
        "0"
    ),
    (
        "2",
        "SEGIN",
        "1478-07-16T05:05:45.251Z",
        "1",
        "une adresse SEGIN",
        "IOI03I9I20I232",
        "lacrim@gmail.com",
        "etat civil",
        'O3U2IO3N2E2IEN23IUOEN',
        "lienfacebook",
        "lien twitter",
        "lien instagram",
        "mot de passe ashe",
        "ayrton",
        "TF",
        "0"
    ),
    (
        "3",
        "TOMATO",
        "2000-07-16T05:05:45.251Z",
        "0",
        "une adresse TOMATO",
        "4292U42942U94U",
        "OMEGALUL@yahoo.net",
        "etat civil",
        '23OIO2IHEO2HIE2',
        "lienfacebook",
        "lien twitter",
        "lien instagram",
        "mot de passe pasher",
        "rapahael",
        "FR",
        "0"
    ),
    (
        "4",
        "BONAPORTE",
        "2021-07-16T05:05:45.251Z",
        "1",
        "une adresse BONANPORT",
        "82492849279274",
        "sky@hotmail.gr",
        "etat civil",
        '29U2N3EN3UDE3D',
        "lienfacebook",
        "lien twitter",
        "lien intzagarm",
        "mot de passer asher",
        "eric",
        "GR",
        "0"
    ),
    (
        "5",
        "LEFEVRE",
        "1998-07-16T05:05:45.251Z",
        "0",
        "une adresse LEFEVRE",
        "294U29429489248",
        "rouquin@outlook.fr",
        "etat civil",
        '3IHE3IUBDI3UBDI3',
        "lienfacebook",
        "lien twitter",
        "lien instagram",
        "mot de passe ashe",
        "andre",
        "PL",
        "0"
    ),
    (
        "6",
        "BONAPORTE",
        "2001-07-16T05:05:45.251Z",
        "0",
        "une adresse BONALPOER",
        "8942849249284",
        "lououou@gmail.com",
        "etat civil",
        '3OUE3INE3IND3IN',
        "lienfacebook",
        "lien twitter",
        "lien instagram",
        "mot de passer asher",
        "jerome",
        "VU",
        "0"
    ),
    (
        "7",
        "LEJEUNE",
        "1974-07-16T05:05:45.251Z",
        "0",
        "une adresse le jeune",
        "2949249284928",
        "jenaimare@msm.net",
        "etat civil",
        '32INE3IN3INDN3',
        "lienfacebook",
        "lien twitter",
        "lien instzgrazm",
        "mot de passe asher",
        "gui",
        "VE",
        "1"
    ),
    (
        "8",
        "SARKO",
        "1956-07-16T05:05:45.251Z",
        "0",
        "une adresse sarko",
        "924294928492",
        "trandom@skyblog.net",
        "etat civil",
        '2IEN3INE3IEN3EI',
        "lienfacebook",
        "lien twitter",
        "lien indtagam",
        "mot de passer asher",
        "chantal",
        "GR",
        "2"
    ),
    (
        "9",
        "DEPARDIEU",
        "1909-07-16T05:05:45.251Z",
        "0",
        "une adresse depardieu",
        "2OU294829849",
        "transandance@gmail.fr",
        "etat civil",
        '2IEN32IN3INE',
        "lienfacebook",
        "lien twitter",
        "lien instagram",
        "mot de passer asher",
        "serge",
        "FR",
        "3"
    );